{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: corerpo-rpo
  namespace: {{ $.Values.namespace | default $.Release.Namespace }}
spec:
  hosts:
    - {{ $.Values.istio.rpo.hostname }}
  gateways:
    - {{ $.Values.istio.gateway }}
  http:
    - route:
      - destination:
          host: rpo
          port:
           number: {{ .Values.rpo.service.port }}
{{- end }}
