apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "project.fullname" . }}-app
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "project.labels" . | indent 4 }}
data:
  application.yaml: |-
{{ toYaml .Values.config | indent 4 }}
