{{- $fullname := include "project.fullname" . }}
{{- range .Values.configFiles }}
{{- $name := .name }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullname }}-{{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "project.labels" $ | indent 4 }}
binaryData: 
  {{ .filename }}: |-
{{ .data | indent 4 }}

---
{{- end }}
