{{- $fullname := include "project.fullname" . }}
{{- if not .Values.stateful }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullname }}
  annotations:
{{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
{{- end }}
  labels:
{{ include "project.labels" . | indent 4 }}
{{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 4 }}
{{- end }}
spec:
  replicas: 1
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app: {{ template "project.name" . }}
      release: {{ .Release.Name }}
  template:
    {{- include "project.podTemplate" . | nindent 4 }}
{{- end }}
