kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "project.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "project.labels" . | indent 4 }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
