apiVersion: v1
kind: Service
metadata:
  name: {{ template "project.fullname" . }}
  labels:
{{ include "project.labels" . | indent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "9090"
      port: 9090
      targetPort: 9090
    {{- if .Values.remotedebug.enabled }}
    - name: {{ .Values.remotedebug.port | default 5005 | quote }}
      port: {{ .Values.remotedebug.port | default 5005 }}
      targetPort: {{ .Values.remotedebug.port | default 5005 }}
    {{- end }}
  selector:
    app: {{ template "project.name" . }}
status:
  loadBalancer: {}
